#' Plays a video and records responses generated with an on-screen slider
#'
#' @param sources Path(s) to the video file. Videos may be specified in multiple formats (e.g., .mp4, .ogg, .webm)
#' @param trial_ends_after_video If TRUE the trial will end as soon as the video finishes playing.
#' @param width The width of the video display in pixels (if NULL, natural width is used)
#' @param height The height of the video display in pixels (if NULL, natural height is used)
#' @param autoplay Does the video play automatically?
#' @param controls Should the video controls be made available to the user?
#' @param rate What rate to play the video (1 = normal, <1 slower, >1 faster)
#'
#' @param labels Labels displayed at equidistant locations on the slider.
#' @param button_label Label placed on the "continue" button
#' @param min Minimum value of the slider
#' @param max Maximum value of the slider
#' @param start Initial value of the slider
#' @param step Step size of the slider
#' @param slider_width Horizontal width of the slider (defaults to 100% of display)
#' @param require_movement Does the user need to move the slider before clicking the continue button?
#'
#' @param prompt A string (may contain HTML) that will be displayed below the stimulus, intended as a reminder about the actions to take (e.g., which key to press).
#' @param trial_duration How long to wait for a response before ending trial in milliseconds. If NULL, the trial will wait indefinitely. If no response is made before the deadline is reached, the response will be recorded as NULL.
#' @param response_ends_trial If TRUE, then the trial will end when a response is made (or the trial_duration expires). If FALSE, the trial continues until the deadline expires.
#'
#' @param post_trial_gap  The gap in milliseconds between the current trial and the next trial. If NULL, there will be no gap.
#' @param on_finish A javascript callback function to execute when the trial finishes
#' @param on_load A javascript callback function to execute when the trial begins, before any loading has occurred
#' @param data An object containing additional data to store for the trial
#'
#' @details This plugin displays an HTML stimulus and records responses generated by a slider. The
#' stimulus can be displayed until a response is given, or for a pre-determined amount of time. The
#' trial can be ended automatically if the subject has failed to respond within a fixed length of time.
#'
#' In addition to the default data collected by all plugins, this plugin collects the following data for
#' each trial: the \code{rt} value is the response time in milliseconds taken for the user to make a
#' response. The time is measured from when the stimulus first appears on the screen until the response;
#' The \code{response} is the numeric value of the slider response. The \code{stimulus} value is
#' a JSON encoding of the sources array.
#'
#' @export
trial_video_slider_response <- function(
  sources,
  trial_ends_after_video = FALSE, # If TRUE the trial will end as soon as the video finishes playing.
  width = NULL, # The width of the video display in pixels (if NULL, natural width is used)
  height = NULL, # The height of the video display in pixels (if NULL, natural height is used)
  autoplay = TRUE, #Does the video play automatically?
  controls = FALSE,
  rate = 1,

  labels = c("0%", "25%", "75%", "100%"),
  min = 0,
  max = 100,
  start = 50,
  step = 1,
  slider_width = NULL,
  require_movement = FALSE,

  prompt = NULL,
  trial_duration = NULL,
  response_ends_trial = TRUE,

  post_trial_gap = 0,  # start universals
  on_finish = NULL,
  on_load = NULL,
  data = NULL
) {
  drop_nulls(
    trial(
      type = "video-slider-response",
      sources = sources,
      trial_ends_after_video = trial_ends_after_video, # If TRUE the trial will end as soon as the video finishes playing.
      width = width, # The width of the video display in pixels (if NULL, natural width is used)
      height = height, # The height of the video display in pixels (if NULL, natural height is used)
      autoplay = autoplay, #Does the video play automatically?
      controls = controls,
      rate = rate,

      labels = labels,
      min = min,
      max = max,
      start = start,
      step = step,
      slider_width = slider_width,
      require_movement = require_movement,

      prompt = prompt,
      trial_duration = trial_duration,
      response_ends_trial = response_ends_trial,

      post_trial_gap = post_trial_gap,
      on_finish = on_finish,
      on_load = on_load,
      data = data
    )
  )
}
