#' Specify a video trial with keyboard response
#'
#' @description The \code{trial_video_keyboard_response} function is used to play
#' a video stimulus and collect a response using a key press.
#'
#' @param sources Path(s) to the video file. Videos may be specified in multiple formats (e.g., .mp4, .ogg, .webm)
#' @param trial_ends_after_video If TRUE the trial will end as soon as the video finishes playing.
#' @param width The width of the video display in pixels (if NULL, natural width is used)
#' @param height The height of the video display in pixels (if NULL, natural height is used)
#' @param autoplay Does the video play automatically?
#' @param controls Should the video controls be made available to the user?
#' @param start Specifies the time in seconds to start the video (if NULL, start at beginning)
#' @param stop Specifies the time in seconds to stop the video (if NULL, stop at end)
#' @param rate What rate to play the video (1 = normal, <1 slower, >1 faster)
#'
#' @param choices A character vector of keycodes (either numeric values or the characters themselves). Alternatively, respond_any_key() and respond_no_key() can be used
#'
#' @param prompt A string (may contain HTML) that will be displayed below the stimulus, intended as a reminder about the actions to take (e.g., which key to press).
#' @param trial_duration How long to wait for a response before ending trial in milliseconds. If NULL, the trial will wait indefinitely. If no response is made before the deadline is reached, the response will be recorded as NULL.
#' @param response_ends_trial If TRUE, then the trial will end when a response is made (or the trial_duration expires). If FALSE, the trial continues until the deadline expires.
#'
#' @param post_trial_gap  The gap in milliseconds between the current trial and the next trial. If NULL, there will be no gap.
#' @param on_finish A javascript callback function to execute when the trial finishes
#' @param on_load A javascript callback function to execute when the trial begins, before any loading has occurred
#' @param data An object containing additional data to store for the trial
#'
#'@return Functions with a \code{trial_} prefix always return a "trial" object.
#' A trial object is simply a list containing the input arguments, with
#' \code{NULL} elements removed. Logical values in the input (\code{TRUE} and
#' \code{FALSE}) are transformed to character vectors \code{"true"} and \code{"false"}
#' and are specified to be objects of class "json", ensuring that they will be
#' written to file as the javascript logicals, \code{true} and \code{false}.
#'
#' @details This plugin displays an HTML stimulus and responses generated by a key press. The
#' stimulus can be displayed until a response is given, or for a pre-determined amount of time. The
#' trial can be ended automatically if the subject has failed to respond within a fixed length of time.
#'
#' The data recorded by this trial is as follows:
#'
#' \itemize{
#' \item The \code{rt} value is the response time in milliseconds taken for the
#' user to make a response. The time is measured from when the stimulus first
#' appears on the screen until the response.
#' \item The \code{key_press} variable is the numeric javascript key code
#' corresponding to the response.
#' \item The \code{stimulus} variable records a JSON encoding of the sources array.
#'}
#'
#' In addition, it records default variables that are recorded by all trials:
#'
#' \itemize{
#' \item \code{trial_type} is a string that records the name of the plugin used to run the trial.
#' \item \code{trial_index} is a number that records the index of the current trial across the whole experiment.
#' \item \code{time_elapsed} counts the number of milliseconds since the start of the experiment when the trial ended.
#' \item \code{internal_node_id} is a string identifier for the current "node" in the timeline.
#' }
#'
#' @export
trial_video_keyboard_response <- function(
  sources,
  trial_ends_after_video = FALSE, # If TRUE the trial will end as soon as the video finishes playing.
  width = NULL, # The width of the video display in pixels (if NULL, natural width is used)
  height = NULL, # The height of the video display in pixels (if NULL, natural height is used)
  autoplay = TRUE, #Does the video play automatically?
  controls = FALSE,
  start = NULL,
  stop = NULL,
  rate = 1,

  choices = respond_any_key(),

  prompt = NULL,
  trial_duration = NULL,
  response_ends_trial = TRUE,

  post_trial_gap = 0,  # start universals
  on_finish = NULL,
  on_load = NULL,
  data = NULL
) {
  drop_nulls(
    trial(
      type = "video-keyboard-response",
      sources = sources,
      trial_ends_after_video = js_logical(trial_ends_after_video), # If TRUE the trial will end as soon as the video finishes playing.
      width = width, # The width of the video display in pixels (if NULL, natural width is used)
      height = height, # The height of the video display in pixels (if NULL, natural height is used)
      autoplay = js_logical(autoplay), #Does the video play automatically?
      controls = js_logical(controls),
      start = start,
      stop = stop,
      rate = rate,

      choices = choices,

      prompt = prompt,
      trial_duration = trial_duration,
      response_ends_trial = js_logical(response_ends_trial),

      post_trial_gap = post_trial_gap,
      on_finish = on_finish,
      on_load = on_load,
      data = data
    )
  )
}
